# np.array( )

In [2]:
import numpy as np
a = np.array([1,2,3])

In [3]:
type(a)

numpy.ndarray

In [5]:
a

array([1, 2, 3])

#### 記憶體位置

In [27]:
a.data

#### 資料型別

In [28]:
a.dtype

dtype('int64')

In [29]:
a.ndim

1

# element wise

In [6]:
a*3

array([3, 6, 9])

In [7]:
a+2

array([3, 4, 5])

In [8]:
b = np.array([2,2,0])

In [9]:
a+b

array([3, 4, 3])

In [10]:
a/b

<ipython-input-10-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([0.5, 1. , inf])

In [11]:
a*b

array([2, 4, 0])

# dtype
#### 更改型別

In [31]:
b1 = np.array([1,2,3], dtype='int32')

In [32]:
b1.dtype

dtype('int32')

In [34]:
b1

array([1, 2, 3], dtype=int32)

In [35]:
c = np.array([0,1,2], dtype='float')

In [36]:
c

array([0., 1., 2.])

In [37]:
d = np.array([3e50,4e35], dtype='int64')

OverflowError: Python int too large to convert to C long

In [39]:
d = np.array([3e50,4e35], dtype='float64')

In [40]:
d

array([3.e+50, 4.e+35])

In [41]:
e = np.array([3.5,4.2,-4.3], dtype='int')

In [42]:
e

array([ 3,  4, -4])

In [43]:
f = np.array([0,3,0,-1], dtype='bool')

In [44]:
f

array([False,  True, False,  True])

# np.arange( )
## np.arange(int)
## np.arange(起始,終點,間距)
### 終點不包含

In [18]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# np.linspace( )
## 0~10用15個數字作均分 包含終點值共14等分

In [26]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])