# append

In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 1D陣列增加
#### ND陣列增加要加上axis參數

In [6]:
np.append(a,[6,4,2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [4]:
b = np.arange(12).reshape((3,4))

In [5]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 多維增加
#### 沒指定axis會傳回1D陣列

In [7]:
np.append(b,[1,2,3,4])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [8]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.append(b,[[1,2,3,4]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

#### 軸數不一至

In [12]:
np.append(b,[1,2,3,4],axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [13]:
c = np.arange(12).reshape((3,4))

In [14]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
d = np.linspace(0,26,12).reshape(3,4)

In [16]:
d

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

#### c後面加上d (3,4) -->(6,4)

In [17]:
np.append(c,d, axis=0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [24]:
w = np.append(c,d, axis=0)

In [25]:
w.shape

(6, 4)

#### axis=1 有4元素 (3,4) --> (3,8)

In [19]:
np.append(c,d, axis=1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])

In [20]:
q = np.append(c,d, axis=1)

In [23]:
q.shape

(3, 8)

# all( )
#### a 全不是0 才True 只要有0就False 
#### 檢查全部array值有沒有0

In [39]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.all(a)

False

In [59]:
a.all()

False

In [30]:
aa = np.ones((3,3))

In [31]:
aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.all(aa)

True

In [60]:
aa.all()

True

#### a<12 True

In [36]:
np.all(a<12)

True

In [65]:
(a<12).all()

True

In [37]:
np.all(aa%3<2)

True

#### axis=0

In [46]:
bb = np.array([[1,1,1],[1,0,1],[1,0,1]])

In [47]:
bb.shape

(3, 3)

#### 111T 100F 111T

In [48]:
bb1 = np.all(bb, axis=0)

In [49]:
bb1

array([ True, False,  True])

#### 變 1D array

In [50]:
bb1.shape

(3,)

#### 111T 101F 101F

In [61]:
np.all(bb, axis=1)

array([ True, False, False])

In [62]:
bb.all(axis=1)

array([ True, False, False])

# keepdims 保留axis

In [55]:
bb2 = np.all(bb, axis=0, keepdims=True)

In [52]:
bb2

array([[ True, False,  True]])

In [53]:
bb2.shape

(1, 3)

In [63]:
a.all(keepdims=True)

array([False])

# any( )
#### a 只要有一個不是0 就True  
#### 檢查全部array值有沒有 符合條件 只要有一個就True

In [66]:
aaa = np.random.randint(10,size=(2,3))

In [67]:
aaa

array([[2, 1, 7],
       [3, 6, 0]])

In [78]:
np.any(aaa)

True

In [72]:
np.any(aaa==9)

False

In [73]:
np.any(aaa==7)

True

In [76]:
np.any(aaa%2==0, axis=0)

array([ True,  True,  True])

In [77]:
np.any(aaa%2==1, axis=1)

array([ True,  True])

In [79]:
np.any(aaa%2==1, axis=1, keepdims=True)

array([[ True],
       [ True]])

In [81]:
np.any(aaa>2, keepdims=True)

array([[ True]])

In [82]:
(aaa%5==0).any()

True

In [83]:
(aaa>3).any()

True

In [85]:
bbb = np.random.randint(10, size=(2,3))

In [86]:
bbb

array([[8, 1, 7],
       [1, 9, 7]])

In [87]:
(aaa==bbb).any(axis=1)

array([ True, False])

In [88]:
(aaa==bbb).any(axis=1, keepdims=True)

array([[ True],
       [False]])