# 二維陣列

In [3]:
import numpy as np
c = np.array([[1,2,3],[4,5,6]])

In [4]:
c

array([[1, 2, 3],
       [4, 5, 6]])

#### 轉置

In [14]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 2x3維的陣列
#### 用.shape檢查形狀

In [5]:
c.shape

(2, 3)

In [9]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### 顯示幾D array

In [15]:
c.ndim

2

#### 轉一維

In [17]:
c.flat

In [19]:
c.data

# 三維陣列

In [6]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

In [7]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [8]:
d.shape

(2, 4, 3)

In [16]:
d.ndim

3

In [18]:
d.flat

In [20]:
a = np.array([[0,1],[2,3],[4,5]])

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b = np.array([a,a])

In [23]:
b

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

In [24]:
b.shape

(2, 3, 2)

#### array([[0+0,1+1],[2+2,3+3],[4+4,5+5]])

In [25]:
b.sum(axis=0)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

#### array([[0+2+4,1+3+5],[0+2+4,1+3+5]])

In [26]:
b.sum(axis=1)

array([[6, 9],
       [6, 9]])

#### array([[0+1,2+3,4+5],[0+1,2+3,4+5]])

In [27]:
b.sum(axis=2)

array([[1, 5, 9],
       [1, 5, 9]])