# 1D-slicing切片

In [1]:
a = [1,2,3,4,5]

In [2]:
a[1:-1]

[2, 3, 4]

In [4]:
import numpy as np

In [5]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[1:5]

array([1, 2, 3, 4])

In [8]:
a[2:8:2]

array([2, 4, 6])

In [9]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
a[:3]

array([0, 1, 2])

In [11]:
a[4:]

array([4, 5, 6, 7, 8, 9])

In [12]:
a[:3],a[3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [13]:
a[::2]

array([0, 2, 4, 6, 8])

In [14]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2D-slicing切片

In [19]:
b = np.arange(20).reshape(4,5)

In [20]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
b[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [22]:
b[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [25]:
b[::2,:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [26]:
b[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

In [27]:
b[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [28]:
b[::-1,::-1]

array([[19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

# Broadcasting陣列擴張
#### 規則1.增軸-軸數不同 左邊捕1
#### 規則2.增維-維度不同 維度為1的軸會擴增維度 與另一軸維度匹配 若任一軸維度沒有1維 則無法擴增 必須是1維

In [35]:
c = np.array([[1,2]])

In [36]:
c

array([[1, 2]])

In [38]:
c.shape

(1, 2)

In [39]:
d = np.array([3,4])

In [40]:
d

array([3, 4])

In [41]:
d.shape

(2,)

In [42]:
c+d

array([[4, 6]])

In [43]:
e = np.array([[3,4],[2,3]])

In [44]:
e

array([[3, 4],
       [2, 3]])

In [45]:
e.shape

(2, 2)

In [46]:
c+e

array([[4, 6],
       [3, 5]])