# 陣列重塑
#### np.reshape

In [32]:
import numpy as np

In [33]:
a = np.arange(12)

In [34]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = np.reshape(a,(3,4))

In [5]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[0,1]=0

In [7]:
b

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### b是參照a物件內容 b改a也改

# resize
#### b改a不動到用resize

In [35]:
j = np.resize(a,(3,4))

In [36]:
j[0,1]=0

In [37]:
j

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
a

array([ 0,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
c = np.arange(12)

In [12]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### C (row-major)

In [10]:
d = np.reshape(c,(3,4),order='C')

In [11]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### F (column-major)

In [13]:
d = np.reshape(c,(3,4),order='F')

In [14]:
d

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

#### 總元素量與原始陣列不一致 在任一軸指定 -1 可以自動求出

In [22]:
np.reshape(c,(3,6))

ValueError: cannot reshape array of size 12 into shape (3,6)

In [16]:
f = np.arange(12)

In [17]:
np.reshape(a, (3,-1))

array([[ 0,  0,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.reshape(a,(-1,6))

array([[ 0,  0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

#### g == h

In [23]:
g = np.arange(12).reshape((3,4))

In [25]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
h = np.arange(12).reshape((3,-1))

In [27]:
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])