# where

In [1]:
import numpy as np

In [2]:
a = np.arange(20, 0, -2)

In [3]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### index 6,7,8,9 

In [4]:
np.where(a < 10)

(array([6, 7, 8, 9]),)

#### array 8,6,4,2

In [5]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [6]:
a1 = np.arange(12).reshape((3,4))

In [7]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.where(a1 % 2 == 0)

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))

In [9]:
a1[np.where(a1 % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

# 置換
#### a1%2==0 True-even False-odd

In [11]:
np.where(a1%2==0, 'even', 'odd')

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [12]:
b = np.reshape(a1, (3,4))

In [13]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
c = b ** 2

In [15]:
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
np.where(b%2==0 , b, c)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

# amax

In [17]:
np.amax(np.array([1,2,3,2,1]))

3

In [18]:
arr = np.array([1,2,3,4]).reshape((2,2))

In [19]:
arr

array([[1, 2],
       [3, 4]])

In [20]:
np.amax(arr, axis=0)

array([3, 4])

In [21]:
np.amax(arr, axis=1)

array([2, 4])

In [22]:
np.amax(arr, keepdims=True)

array([[4]])

In [23]:
b1 = np.random.randint(30, size=(2,3,5))

In [24]:
b1

array([[[28,  4, 27, 27,  1],
        [ 7, 20,  8, 20, 13],
        [24,  8, 14, 26,  6]],

       [[12, 11, 26, 12,  9],
        [27,  0,  8, 20, 15],
        [ 2, 20, 25, 29, 26]]])

In [25]:
b1.max(axis=0)

array([[28, 11, 27, 27,  9],
       [27, 20,  8, 20, 15],
       [24, 20, 25, 29, 26]])

In [26]:
b1.max(axis=1)

array([[28, 20, 27, 27, 13],
       [27, 20, 26, 29, 26]])

In [27]:
b1.max(axis=2)

array([[28, 20, 26],
       [26, 27, 29]])

# amin

In [32]:
b1.min(axis=0, keepdims=True)

array([[[12,  4, 26, 12,  1],
        [ 7,  0,  8, 20, 13],
        [ 2,  8, 14, 26,  6]]])

In [33]:
b1.min(axis=1, keepdims=True)

array([[[ 7,  4,  8, 20,  1]],

       [[ 2,  0,  8, 12,  9]]])

In [34]:
b1.min(axis=2, keepdims=True)

array([[[1],
        [7],
        [6]],

       [[9],
        [0],
        [2]]])